### ISSUE TITLE
[BUG] Polymorpher not working anymore

### ISSUE THREAD

**Issue by mortiferus93** [p4535992/foundryvtt-automated-polymorpher#13]
**Module Version:** v1.0.34

**Describe the bug**
Polymorph via the polymorpher doesn't work anymore. Vanilla polymorph is working.

**To Reproduce**
1. Open Polymopher
2. Add new actor to polymorph in via drag and drop to the manager
3. Click on the icon to polymorph in
4. Visual effect appears, but neither token nor sheet changes

**Expected behavior**

**Foundry Version:** 
latest v9

**Game System:** 
latest 5e

**Comment by p4535992** [comment]
should be solved let me know it

**Comment by mortiferus93** [comment]
unfortunately it still does not work

**Comment by gioppoluca** [comment]
still not working: using wild shape is not properly changing the sheet.
Foundry Version 10.285, module version 1.0.43

**Comment by p4535992** [comment]
Sorry, but between limited free time and the fact that I am not exceptional with code I am forced to abandon the module I have opened a ticket for anyone interested to coordinate to rewrite a new one https://discord.com/channels/732325252788387980/1076817951623229500
